[package]
name = "compiler-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bon = "2.3.0"
clap = { version = "4.5.20", features = ["derive"] }
once_cell = "1.20.2"
regex = "1.11.0"
